name: Welcome New Contributors
on:
pull_requests_target:
types:[opened]

jobs:
   greet:
    runs-on :ubuntu-latest
	steps:
	-name: Greet the contributor
	 uses: actions/first-interaction@v1
	with:
	repo-taken:${{secrets.GITHUB_TAKEN}}
	pr-message:
	Thanks for opening your first pull request!
	We're happy to have your contribution.Let us know if you need any help!
